version: 2
updates:
  # Enable version updates for NuGet packages
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:00"
      timezone: "UTC"
    open-pull-requests-limit: 10
    reviewers:
      - "your-github-username" # Replace with actual reviewer
    assignees:
      - "your-github-username" # Replace with actual assignee
    commit-message:
      prefix: "chore"
      include: "scope"
    labels:
      - "dependencies"
      - "nuget"
    ignore:
      # Ignore major version updates for critical packages
      - dependency-name: "Microsoft.EntityFrameworkCore*"
        update-types: ["version-update:semver-major"]
      - dependency-name: "Microsoft.AspNetCore*"
        update-types: ["version-update:semver-major"]
  # Enable version updates for Docker
  - package-ecosystem: "docker"
    directory: "/ParkingApi/src"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "08:00"
      timezone: "UTC"
    open-pull-requests-limit: 5
    reviewers:
      - "your-github-username"
    commit-message:
      prefix: "chore"
      include: "scope"
    labels:
      - "dependencies"
      - "docker"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "08:00"
      timezone: "UTC"
    open-pull-requests-limit: 5
    reviewers:
      - "your-github-username"
    commit-message:
      prefix: "chore"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"
