version: "3.8"
services:
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./monitoring/prometheus:/etc/prometheus
    ports:
      - 9090:9090

  alertmanager:
    image: prom/alertmanager:latest
    volumes:
      - ./monitoring/alertmanager:/etc/alertmanager
    ports:
      - 9093:9093

  node-exporter:
    image: prom/node-exporter:latest
    ports:
      - 9100:9100

networks:
  iot-network:
    driver: bridge
  loki-network:
    driver: bridge
