# filepath: c:\Users\ap-ip\OneDrive\Рабочий стол\ITMO\highload-2025\docker-compose.tests.yml
version: "3.8"

services:
  postgres-test:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: parking_test
    ports:
      - "5433:5432"
    volumes:
      - ./ParkingApi/tests/ParkingApi.IntegrationTests/init-scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres-test-data:/var/lib/postgresql/data
    networks:
      - test-network

  influxdb-test:
    image: influxdb:2.7
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=password12345
      - DOCKER_INFLUXDB_INIT_ORG=test-org
      - DOCKER_INFLUXDB_INIT_BUCKET=iot_bucket
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=my-super-secret-auth-token
    ports:
      - "18086:8086"
    volumes:
      - influxdb-test-data:/var/lib/influxdb2
    networks:
      - test-network

  mosquitto-test:
    image: eclipse-mosquitto:2.0
    ports:
      - "1884:1883"
    volumes:
      - ./mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
    networks:
      - test-network

  data-simulator-test:
    build:
      context: .
      dockerfile: data_simulator/tests/Dockerfile
    depends_on:
      - postgres-test
      - mosquitto-test
    environment:
      - MQTT_HOST=mosquitto-test
      - POSTGRES_HOST=postgres-test
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=parking_test
    networks:
      - test-network

  iot-controller-test:
    build:
      context: .
      dockerfile: iot_controller/tests/Dockerfile
    depends_on:
      - influxdb-test
      - mosquitto-test
    environment:
      - MQTT_HOST=mosquitto-test
      - INFLUXDB_URL=http://influxdb-test:8086
      - INFLUXDB_TOKEN=my-super-secret-auth-token
      - INFLUXDB_ORG=test-org
    networks:
      - test-network

volumes:
  postgres-test-data:
  influxdb-test-data:

networks:
  test-network:
    driver: bridge
