global:
  resolve_timeout: 5m
  smtp_smarthost: 'localhost:1025'
  smtp_from: 'alertmanager@iot-parking.local'
  smtp_require_tls: false

route:
  group_by: ['alertname', 'severity']
  group_wait: 10s
  group_interval: 30s
  repeat_interval: 12h
  receiver: 'default-notifications'
  routes:
  - match:
      severity: critical
    receiver: 'critical-alerts'
    group_wait: 5s
    repeat_interval: 1h
  - match:
      severity: warning
    receiver: 'warning-alerts'

receivers:
- name: 'default-notifications'
  webhook_configs:
  - url: 'http://host.docker.internal:8090/webhook'
    send_resolved: true

- name: 'critical-alerts'
  webhook_configs:
  - url: 'http://host.docker.internal:8090/webhook'
    send_resolved: true

- name: 'warning-alerts'
  webhook_configs:
  - url: 'http://host.docker.internal:8090/webhook'
    send_resolved: true

inhibit_rules:
- source_match:
    severity: 'critical'
  target_match:
    severity: 'warning'
  equal: ['alertname', 'instance']