groups:
- name: basic_alerts
  rules:
  - alert: HighCpuUsage
    expr: 100 - (avg by(instance) (irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "High CPU usage detected (instance {{ $labels.instance }})"
      description: "CPU usage is above 80% for 5 minutes\n  VALUE = {{ $value }}%\n  LABELS = {{ $labels }}"

  - alert: HighMemoryUsage
    expr: (1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) * 100 > 75
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "High memory usage detected (instance {{ $labels.instance }})"
      description: "Memory usage is above 75% for 5 minutes\n  VALUE = {{ $value }}%\n  LABELS = {{ $labels }}"

  - alert: ServiceDown
    expr: up == 0
    for: 30s
    labels:
      severity: critical
    annotations:
      summary: "Service down (instance {{ $labels.instance }})"
      description: "Service {{ $labels.job }} is down for more than 30 seconds\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"