global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - alerts.yml
  - /etc/prometheus/grafana-alert-rules.yml

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - alertmanager:9093

scrape_configs:
  - job_name: "node-exporter"
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: "prometheus"
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: "alertmanager"
    static_configs:
      - targets: ['alertmanager:9093']
      
  - job_name: "influxdb"
    static_configs:
      - targets: ['influxdb:8086']

  - job_name: "api"
    static_configs:
      - targets: ['api:8000']

  # Mosquitto не предоставляет метрики Prometheus по умолчанию
  # Нужен специальный exporter для MQTT метрик