global:
  scrape_interval: 15s

rule_files:
  - alerts.yml

scrape_configs:
  - job_name: "node-exporter"
    static_configs:
      - targets: ['node-exporter:9100'] # Порт метрик ваших сервисов

  - job_name: "api"
    static_configs:
      - targets: ['api:8000']  # ParkingApi

  - job_name: "influxdb"
    static_configs:
      - targets: ['influxdb:8086']

  - job_name: "mosquitto"
    static_configs:
      - targets: ['mosquitto:1883']

  - job_name: "prometheus"
    static_configs:
      - targets: ['prometheus:9090']